### ISSUE TITLE
cvmfs-contrib apt repository failure on ubuntu

### ISSUE THREAD

**Issue by astroclark** [cvmfs-contrib/cvmfs-contrib.github.io#3] opened 2021-04-01 23:05 UTC
I'm setting up a new Ubuntu 20.04 laptop with cvmfs.   Installing the repo package goes ok with the following warning about falling back to 18.04:
```
$ sudo dpkg -i cvmfs-contrib-release-latest_all.deb                                               
(Reading database ... 220963 files and directories currently installed.)
Preparing to unpack cvmfs-contrib-release-latest_all.deb ...
Unpacking cvmfs-contrib-release (1.12.1) over (1.12.1) ...
Setting up cvmfs-contrib-release (1.12.1) ...
Warning: Ubuntu_20.04 is not supported.  Using Ubuntu_18.04 instead.
```
but the repo does not have a release file so the `apt update` fails:
```
Err:12 http://downloadcontent.opensuse.org/repositories/home:/cvmfs:/contrib/Ubuntu_18.04 ./ Release                                                     
  404  Not Found [IP: 195.135.221.157 80]
<snip>
E: The repository 'http://downloadcontent.opensuse.org/repositories/home:/cvmfs:/contrib/Ubuntu_18.04 ./ Release' does not have a Release file
```
I have installed cvmfs in Ubuntu before (different machine, some years ago) so maybe I'm forgetting a critical step?

**Comment by DrDaveD** [comment] 2021-04-02 12:07
This is a duplicate of [cvmfs-contrib-release #14](https://github.com/cvmfs-contrib/cvmfs-contrib-release/issues/14).  It has been fixed in [cvmfs-contrib-release_1.13.1](https://download.opensuse.org/repositories/home:/cvmfs:/contrib/xUbuntu_20.04/all/cvmfs-contrib-release_1.13.1-1_all.deb) but not yet made it to cvmfs-contrib-release-latest_all.deb.

**Closed as completed by DrDaveD** 2021-04-02 12:07 UTC
